### ISSUE TITLE
How to integrate this with OwinStartup?

### ISSUE THREAD

**Issue by cosmoKenney** [Jehoel/AspNetDependencyInjection#6]
I've got my old web forms project setup to now include MVC. And I have automatic startup via OwinStartup:
```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Owin;
using Owin;
using System.Web.Mvc;

[assembly: OwinStartup( typeof( ProvPubs.Compline.Web.Startup ) )]
namespace ProvPubs.Compline.Web
{
	public partial class Startup
	{
		public void Configuration( IAppBuilder app )
		{
			var services = new ServiceCollection( );
			ConfigureServices( services );
			var resolver = new DefaultDependencyResolver( services.BuildServiceProvider( ) );
			DependencyResolver.SetResolver( resolver );
			ConfigureAuth( app );
		}
	}
}
```
My services are registered in a partial (Startup) class. 
But since my startup is automatically called by the framework, how would I incorporate your project such that I can use constructor di in aspx pages?

**Comment by Jehoel** [comment]
@cosmoKenney You'll want to use `WebActivatorEx` as per the examples in the documentation.

This is because `WebActivatorEx.PreStart` runs *before* `OwinStartup`: https://stackoverflow.com/questions/21462777/webactivatorex-vs-owinstartup

The ASP.NET MVC functionality in `AspNetDependencyInjection` doesn't work right now, but I've got a fix in the works I'll publish shortly - in a few hours.

**Comment by Jehoel** [comment]
@cosmoKenney Did my reply help? May I close this issue now?

**Comment by cosmoKenney** [comment]
Yes I believe so.
